/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package student;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author Dummy
 */
public class SelectStudent extends javax.swing.JFrame {


    
    public Connection con;
    public Statement s;
    public String query;
    public ResultSet rs1,rs2,rs3,rs4,rs5,rs6,rs7,rs8;
    public String regno, rollno;
    public static String datasource;
    
    public SelectStudent() {
        initComponents();
         ImageIcon X = new ImageIcon (AdminPanel.class.getResource("images/pec.jpg"));
        pec.setIcon(X);
        ImageIcon Y = new ImageIcon (AdminPanel.class.getResource("images/au.png"));
        au.setIcon(Y);
        select.add(regnoradio);
        select.add(rollnoradio);
        
        try{
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con = DriverManager.getConnection("jdbc:odbc:"+datasource,"","");
        } 
           catch (ClassNotFoundException ex) {
            System.out.println("Class Not Found");
        } catch (SQLException ex) {
            System.out.println("connection not established");
        }
    }
    
    public String no,first,ssem1=null,ssem2=null,ssem3=null,ssem4=null,ssem5=null,ssem6=null,ssem7=null,ssem8=null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        select = new javax.swing.ButtonGroup();
        selectlbl = new javax.swing.JLabel();
        regno1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        s1 = new javax.swing.JCheckBox();
        s2 = new javax.swing.JCheckBox();
        s3 = new javax.swing.JCheckBox();
        s4 = new javax.swing.JCheckBox();
        s5 = new javax.swing.JCheckBox();
        s6 = new javax.swing.JCheckBox();
        s7 = new javax.swing.JCheckBox();
        s8 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        regnoradio = new javax.swing.JRadioButton();
        rollnoradio = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        au = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pec = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectlbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        selectlbl.setText("REGISTER NO");

        regno1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        regno1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                regno1FocusLost(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("SEMESTER");

        s1.setText("1");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        s2.setText("2");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        s3.setText("3");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        s4.setText("4");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        s5.setText("5");
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });

        s6.setText("6");
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });

        s7.setText("7");
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s7ActionPerformed(evt);
            }
        });

        s8.setText("8");
        s8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s8ActionPerformed(evt);
            }
        });

        jButton1.setText("FIND");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("SELECT BY ");

        regnoradio.setText("REG NO");
        regnoradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regnoradioActionPerformed(evt);
            }
        });

        rollnoradio.setText("ROLL NO");
        rollnoradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollnoradioActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setText("PANIMALAR ENGINEERING COLLEGE");

        au.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        au.setMaximumSize(new java.awt.Dimension(64, 64));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("RESULT MAINTAINENCE PORTAL");

        pec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pec.setMaximumSize(new java.awt.Dimension(64, 64));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(pec, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(au, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s4)
                                .addGap(18, 18, 18)
                                .addComponent(s5)
                                .addGap(18, 18, 18)
                                .addComponent(s6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s1)
                                .addGap(18, 18, 18)
                                .addComponent(s2)
                                .addGap(18, 18, 18)
                                .addComponent(s3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(s7)
                                .addGap(18, 18, 18)
                                .addComponent(s8))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selectlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regno1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(regnoradio)
                                .addGap(18, 18, 18)
                                .addComponent(rollnoradio)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(au, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(pec, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(regnoradio)
                        .addComponent(rollnoradio))
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(s1)
                    .addComponent(s2)
                    .addComponent(s3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s4)
                    .addComponent(s5)
                    .addComponent(s6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(s7)
                    .addComponent(s8))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        DisplayResults d = new DisplayResults();
        this.setVisible(false);
        d.setVisible(true);
        String endresult = first;
        if( ssem1 != null ) 
            endresult  = endresult + ssem1;
        if( ssem2 != null ) 
            endresult  = endresult + ssem2;
        if( ssem3 != null ) 
            endresult  = endresult + ssem3;
        if( ssem4 != null ) 
            endresult  = endresult + ssem4;
        if( ssem5 != null ) 
            endresult  = endresult + ssem5;
        if( ssem6 != null ) 
            endresult  = endresult + ssem6;
        if( ssem7 != null ) 
            endresult  = endresult + ssem7;
        if( ssem8 != null ) 
            endresult  = endresult + ssem8;
        
        d.results.setText(endresult);
        d.flag = 2;
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public String filter;
    
    private void regnoradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regnoradioActionPerformed
        if ( regnoradio.isSelected())
        { selectlbl.setText("REGISTER NO"); filter = "REGISTERNO"; }
        else
        {    selectlbl.setText("ROLL NO"); filter = "ROLLNO"; }
    }//GEN-LAST:event_regnoradioActionPerformed

    private void rollnoradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollnoradioActionPerformed
        if ( regnoradio.isSelected())
        {    selectlbl.setText("REGISTER NO"); filter = "REGISTERNO"; }
        else
        {    selectlbl.setText("ROLL NO"); filter = "ROLLNO"; }
    }//GEN-LAST:event_rollnoradioActionPerformed

    
    
    private void regno1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_regno1FocusLost
        try {
            no = regno1.getText();
            
            query = "select NAME, REGISTERNO, ROLLNO from SEM1 where "+filter+" = '"+no + "'";
            System.out.println(query);
            
            s = con.createStatement();
            s.execute(query);
            
            
            ResultSet rst = s.getResultSet();
            
           
            if ( rst.next() ){
                 Border border = BorderFactory.createLineBorder(new Color(0,200,0), 2);
                regno1.setBorder(border);
                String a = rst.getString("REGISTERNO");
                String b = rst.getString("NAME");
                String c = rst.getString("ROLLNO");
                
                System.out.println(a + b + c ); 
                first = "<html> <body> <table border=\"1\" style=\"width:100%\"> <tr> <td> <b>NAME:</b> </td> <td> "+ b + " </td></tr> <tr><td> <b>REGISTER NO: </b></td><td>"+ a + " </td></tr> <tr><td> <b>ROLL NO: </b></td><td>"+ c + "</td></tr></table>";
            }
            else{
                JOptionPane.showMessageDialog(null, "REGISTER NO NOT FOUND");
                Border border = BorderFactory.createLineBorder(Color.RED, 2);
                regno1.setBorder(border);
                regno1.requestFocus();
            }
            System.out.println(first);
        }
        catch( SQLException e ){ System.out.println(e);}
    }//GEN-LAST:event_regno1FocusLost

    public String carr="",tarr="",gpa="",cgpa="";
    
    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
         
        try {
            query = "select * from SEM1 where "+filter+ " = '"+no + "'";
            s.execute(query);
            rs1 = s.getResultSet();
            String hs6151 = "", ma6151 = "", ph6151 = "", cy6151 = "", ge6151 = "", ge6152 = "", ge6161 = "",ge6162 = "",ge6163 = "";
            while( rs1.next()){
               hs6151 = " <tr> <td> TECH ENG I </td> <td> " + rs1.getString("HS6151") + "</td> </tr>";
               ma6151 = " <tr> <td> MATHEMATICS I </td> <td> " + rs1.getString("MA6151") + "</td> </tr>";
               ph6151 = " <tr> <td> ENGG PHYSICS I </td> <td> " + rs1.getString("PH6151") + "</td> </tr>";
               cy6151 = " <tr> <td> ENGG CHEMISTRY I </td> <td> " + rs1.getString("CY6151") + "</td> </tr>";
               ge6151 = " <tr> <td> COMP PROG </td> <td> " + rs1.getString("GE6151") + "</td> </tr>";
               ge6152 = " <tr> <td> ENGG GRAPHICS </td> <td> " + rs1.getString("GE6152") + "</td> </tr>";
               ge6161 = " <tr> <td> ENGG PRACTICES LAB </td> <td> " + rs1.getString("GE6161") + "</td> </tr>";
               ge6162 = " <tr> <td> COMP PROG LAB </td> <td> " + rs1.getString("GE6162") + "</td> </tr>";
               ge6163 = " <tr> <td> PHY CHEM LAB </td> <td> " + rs1.getString("GE6163") + "</td> </tr>";
               gpa = " <tr> <td> <b>GPA </b></td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("GPA") )) + "</td> </tr>";
               cgpa = " <tr> <td> <b>CGPA</b> </td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("CGPA") )) + "</td> </tr>";
               carr = " <tr> <td> <b>CURRENT ARREAR </b></td> <td> " + rs1.getInt("CURRENTARR") + "</td> </tr>";
               tarr = " <tr> <td> <b>TOTAL ARREAR </b></td> <td> " + rs1.getInt("TOTALARR") + "</td> </tr>";
               
            }
            ssem1 = "<p><center><b> SEMESTER 1 </b></center></p><br> <table border=\"1\" style=\"width:100%\" font-size=\"300%\" > <tr bgcolor = red> <td> SUBJECT </td> <td> GRADE </td> </tr>" + hs6151 + ma6151 + ph6151 + cy6151 + ge6151 + ge6152 + ge6161 + ge6162 + ge6163 + carr + tarr + gpa +cgpa+ "</table> <br> <br>";
        }
        catch(SQLException e){}
        
    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        try {
            query = "select * from SEM2 where "+filter+ " = '"+no + "'";
            s.execute(query);
            rs1 = s.getResultSet();
            String hs6251 = "", ma6251 = "", ph6251 = "", cy6251 = "", ge6251 = "", ge6252 = "", ge6261 = "",ge6262 = "",ge6263 = "";
            while( rs1.next()){
               hs6251 = " <tr> <td> TECH ENG II </td> <td> " + rs1.getString("HS6251") + "</td> </tr>";
               ma6251 = " <tr> <td> MATHEMATICS II </td> <td> " + rs1.getString("MA6251") + "</td> </tr>";
               ph6251 = " <tr> <td> ENGG PHYSICS II </td> <td> " + rs1.getString("PH6251") + "</td> </tr>";
               cy6251 = " <tr> <td> ENGG CHEMISTRY II </td> <td> " + rs1.getString("CY6251") + "</td> </tr>";
               ge6251 = " <tr> <td> DPSD </td> <td> " + rs1.getString("CS6201") + "</td> </tr>";
               ge6252 = " <tr> <td> PDS I </td> <td> " + rs1.getString("CS6202") + "</td> </tr>";
               ge6261 = " <tr> <td> PHY CHEM LAB </td> <td> " + rs1.getString("GE6262") + "</td> </tr>";
               ge6262 = " <tr> <td> DIGITAL LAB </td> <td> " + rs1.getString("CS6211") + "</td> </tr>";
               ge6263 = " <tr> <td> PDS LAB </td> <td> " + rs1.getString("CS6212") + "</td> </tr>";
               gpa = " <tr> <td> <b>GPA </b></td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("GPA") )) + "</td> </tr>";
               cgpa = " <tr> <td> <b>CGPA</b> </td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("CGPA") )) + "</td> </tr>";
               carr = " <tr> <td> <b>CURRENT ARREAR </b></td> <td> " + rs1.getInt("CURRENTARR") + "</td> </tr>";
               tarr = " <tr> <td> <b>TOTAL ARREAR </b></td> <td> " + rs1.getInt("TOTALARR") + "</td> </tr>";
            }
            ssem2 = " <p><center><b> SEMESTER 2 </b></center></p><br><table border=\"1\" style=\"width:100%\" font-size=\"300%\" > <tr bgcolor = red> <td> SUBJECT </td> <td> GRADE </td> </tr>" + hs6251 + ma6251 + ph6251 + cy6251 + ge6251 + ge6252 + ge6261 + ge6262 + ge6263 + carr + tarr + gpa +cgpa+"</table> <br> <br>";
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
         try {
            query = "select * from SEM3 where "+filter+ " = '"+no + "'";
            s.execute(query);
            rs1 = s.getResultSet();
            String hs6151 = "", ma6151 = "", ph6151 = "", cy6151 = "", ge6151 = "", ge6152 = "", ge6161 = "",ge6162 = "",ge6163 = "";
            while( rs1.next()){
               hs6151 = " <tr> <td> TPDE </td> <td> " + rs1.getString("MA6351") + "</td> </tr>";
               ma6151 = " <tr> <td> PDS II </td> <td> " + rs1.getString("CS6301") + "</td> </tr>";
               ph6151 = " <tr> <td> DBMS </td> <td> " + rs1.getString("CS6302") + "</td> </tr>";
               cy6151 = " <tr> <td> CA </td> <td> " + rs1.getString("CS6303") + "</td> </tr>";
               ge6151 = " <tr> <td> ADC </td> <td> " + rs1.getString("CS6304") + "</td> </tr>";
               ge6152 = " <tr> <td> EVS </td> <td> " + rs1.getString("GE6351") + "</td> </tr>";
               ge6161 = " <tr> <td> PDS II LAB </td> <td> " + rs1.getString("CS6311") + "</td> </tr>";
               ge6162 = " <tr> <td> DBMS LAB </td> <td> " + rs1.getString("CS6312") + "</td> </tr>";
                gpa = " <tr> <td> <b>GPA </b></td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("GPA") )) + "</td> </tr>";
               cgpa = " <tr> <td> <b>CGPA</b> </td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("CGPA") )) + "</td> </tr>";
               carr = " <tr> <td> <b>CURRENT ARREAR </b></td> <td> " + rs1.getInt("CURRENTARR") + "</td> </tr>";
               tarr = " <tr> <td> <b>TOTAL ARREAR </b></td> <td> " + rs1.getInt("TOTALARR") + "</td> </tr>";
       
            }
            ssem3 = " <p><center><b> SEMESTER 3 </b></center></p><br><table border=\"1\" style=\"width:100%\" font-size=\"300%\"> <tr bgcolor = red> <td> SUBJECT </td> <td> GRADE </td> </tr>" + hs6151 + ma6151 + ph6151 + cy6151 + ge6151 + ge6152 + ge6161 + ge6162 +carr + tarr + gpa +cgpa+ "</table> <br> <br>";
        }
        catch(SQLException e){e.printStackTrace();}
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
         try {
            query = "select * from SEM4 where "+filter+ " = '"+no + "'";
            s.execute(query);
            rs1 = s.getResultSet();
            String hs6151 = "", ma6151 = "", ph6151 = "", cy6151 = "", ge6151 = "", ge6152 = "", ge6161 = "",ge6162 = "",ge6163 = "";
            while( rs1.next()){
               hs6151 = " <tr> <td> PQT </td> <td> " + rs1.getString("MA6453") + "</td> </tr>";
               ma6151 = " <tr> <td> CN </td> <td> " + rs1.getString("CS6551") + "</td> </tr>";
               ph6151 = " <tr> <td> OS </td> <td> " + rs1.getString("CS6401") + "</td> </tr>";
               cy6151 = " <tr> <td> DAA </td> <td> " + rs1.getString("CS6402") + "</td> </tr>";
               ge6151 = " <tr> <td> SE </td> <td> " + rs1.getString("CS6403") + "</td> </tr>";
               ge6152 = " <tr> <td> MP </td> <td> " + rs1.getString("EC6504") + "</td> </tr>";
               ge6161 = " <tr> <td> CN LAB </td> <td> " + rs1.getString("CS6411") + "</td> </tr>";
               ge6162 = " <tr> <td> MP LAB </td> <td> " + rs1.getString("CS6412") + "</td> </tr>";
               ge6163 = " <tr> <td> OS LAB </td> <td> " + rs1.getString("CS6413") + "</td> </tr>";
            }
            ssem4 = " <p><center><b> SEMESTER 4 </b></center></p><br><table border=\"1\" style=\"width:100%\"> <tr bgcolor = red> <td> SUBJECT </td> <td> GRADE </td> </tr>" + hs6151 + ma6151 + ph6151 + cy6151 + ge6151 + ge6152 + ge6161 + ge6162 + ge6163 + carr + tarr + gpa +cgpa + "</table> <br> <br>";
        }
        catch(SQLException e){e.printStackTrace();}
    }//GEN-LAST:event_s4ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
         try {
            query = "select * from SEM5 where "+filter+ " = '"+no + "'";
            s.execute(query);
            rs1 = s.getResultSet();
            String hs6151 = "", ma6151 = "", ph6151 = "", cy6151 = "", ge6151 = "", ge6152 = "", ge6161 = "",ge6162 = "",ge6163 = "";
            while( rs1.next()){
               hs6151 = " <tr> <td> DM </td> <td> " + rs1.getString("MA6566") + "</td> </tr>";
               ma6151 = " <tr> <td> IP </td> <td> " + rs1.getString("CS6501") + "</td> </tr>";
               ph6151 = " <tr> <td> OOAD </td> <td> " + rs1.getString("CS6502") + "</td> </tr>";
               cy6151 = " <tr> <td> TOC </td> <td> " + rs1.getString("CS6503") + "</td> </tr>";
               ge6151 = " <tr> <td> CG </td> <td> " + rs1.getString("CS6504") + "</td> </tr>";
               ge6152 = " <tr> <td> CASE TOOLS LAB </td> <td> " + rs1.getString("CS6511") + "</td> </tr>";
               ge6161 = " <tr> <td> IP LAB </td> <td> " + rs1.getString("CS6512") + "</td> </tr>";
               ge6162 = " <tr> <td> CG LAB </td> <td> " + rs1.getString("CS6513") + "</td> </tr>";
               gpa = " <tr> <td> <b>GPA </b></td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("GPA") )) + "</td> </tr>";
               cgpa = " <tr> <td> <b>CGPA</b> </td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("CGPA") )) + "</td> </tr>";
               carr = " <tr> <td> <b>CURRENT ARREAR </b></td> <td> " + rs1.getInt("CURRENTARR") + "</td> </tr>";
               tarr = "<tr> <td> <b>TOTAL ARREAR </b></td> <td> " + rs1.getInt("TOTALARR") + "</td> </tr>";
           
              
            }
            ssem5 = "<p><center><b> SEMESTER 5 </b></center></p><br> <table border=\"1\" style=\"width:100%\"> <tr bgcolor = red> <td> SUBJECT </td> <td> GRADE </td> </tr>" + hs6151 + ma6151 + ph6151 + cy6151 + ge6151 + ge6152 + ge6161 + ge6162 + carr + tarr + gpa +cgpa+ "</table> <br> <br>";
        }
        catch(SQLException e){ e.printStackTrace();}
    }//GEN-LAST:event_s5ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        try {
            query = "select * from SEM6 where "+filter+ " = '"+no + "'";
            s.execute(query);
            rs1 = s.getResultSet();
            String hs6251 = "", ma6251 = "", ph6251 = "", cy6251 = "", ge6251 = "", ge6252 = "", ge6261 = "",ge6262 = "",ge6263 = "";
            while( rs1.next()){
               hs6251 = " <tr> <td> DISTRIBUTED SYSTEMS </td> <td> " + rs1.getString("CS6601") + "</td> </tr>";
               ma6251 = " <tr> <td> MOBILE COMPUTING </td> <td> " + rs1.getString("IT6601") + "</td> </tr>";
               ph6251 = " <tr> <td> COMPILER DESIGN </td> <td> " + rs1.getString("CS6660") + "</td> </tr>";
               cy6251 = " <tr> <td> DIGITAL SIGNAL PROCESSING </td> <td> " + rs1.getString("IT6502") + "</td> </tr>";
               ge6251 = " <tr> <td> ARTIFICIAL INTELLIGENCE </td> <td> " + rs1.getString("CS6659") + "</td> </tr>";
               ge6252 = " <tr> <td> ELECTIVE 1 (ST/C#) </td> <td> " + rs1.getString("ELE1") + "</td> </tr>";
               ge6261 = " <tr> <td> MOBILE APP DEVELOPMENT LAB </td> <td> " + rs1.getString("CS6611") + "</td> </tr>";
               ge6262 = " <tr> <td> COMPILER LAB </td> <td> " + rs1.getString("CS6612") + "</td> </tr>";
               ge6263 = " <tr> <td> COMMUNICATION LAB </td> <td> " + rs1.getString("CS6613") + "</td> </tr>";
               gpa = " <tr> <td> <b>GPA </b></td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("GPA") )) + "</td> </tr>";
               cgpa = " <tr> <td> <b>CGPA</b> </td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("CGPA") )) + "</td> </tr>";
               carr = " <tr> <td> <b>CURRENT ARREAR </b></td> <td> " + rs1.getInt("CURRENTARR") + "</td> </tr>";
               tarr = " <tr> <td> <b>TOTAL ARREAR </b></td> <td> " + rs1.getInt("TOTALARR") + "</td> </tr>";
            }
            ssem6 = " <p><center><b> SEMESTER 6 </b></center></p><br><table border=\"1\" style=\"width:100%\" font-size=\"300%\" > <tr bgcolor = red> <td> SUBJECT </td> <td> GRADE </td> </tr>" + hs6251 + ma6251 + ph6251 + cy6251 + ge6251 + ge6252 + ge6261 + ge6262 + ge6263 + carr + tarr + gpa +cgpa+"</table> <br> <br>";
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_s6ActionPerformed

    private void s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s7ActionPerformed
        try {
            query = "select * from SEM7 where "+filter+ " = '"+no + "'";
            s.execute(query);
            rs1 = s.getResultSet();
            String hs6251 = "", ma6251 = "", ph6251 = "", cy6251 = "", ge6251 = "", ge6252 = "", ge6261 = "",ge6262 = "",ge6263 = "";
            while( rs1.next()){
               hs6251 = " <tr> <td> CRYTOGRAPHY AND NETWORK SECURITY </td> <td> " + rs1.getString("CS6701") + "</td> </tr>";
               ma6251 = " <tr> <td> GRAPH THEORY AND APPLICATIONS</td> <td> " + rs1.getString("CS6702") + "</td> </tr>";
               ph6251 = " <tr> <td> GRID AND CLOUD COMPUTING</td> <td> " + rs1.getString("CS6703") + "</td> </tr>";
               cy6251 = " <tr> <td> RESOURCE MANAGEMENT TECHNIQUES </td> <td> " + rs1.getString("CS6704") + "</td> </tr>";
               ge6251 = " <tr> <td> SERVICE ORIENTED ARCHITECTURE</td> <td> " + rs1.getString("ELE2") + "</td> </tr>";
               ge6252 = " <tr> <td> INFORMATION RETRIEVAL</td> <td> " + rs1.getString("ELE3") + "</td> </tr>";
               ge6261 = " <tr> <td> SECURITY LAB </td> <td> " + rs1.getString("CS6711") + "</td> </tr>";
               ge6262 = " <tr> <td> GRID AND CLOUD COMPUTING LAB </td> <td> " + rs1.getString("CS6712") + "</td> </tr>";
               gpa = " <tr> <td> <b>GPA </b></td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("GPA") )) + "</td> </tr>";
               cgpa = " <tr> <td> <b>CGPA</b> </td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("CGPA") )) + "</td> </tr>";
               carr = " <tr> <td> <b>CURRENT ARREAR </b></td> <td> " + rs1.getInt("CURRENTARR") + "</td> </tr>";
               tarr = " <tr> <td> <b>TOTAL ARREAR </b></td> <td> " + rs1.getInt("TOTALARR") + "</td> </tr>";
            }
            ssem7 = " <p><center><b> SEMESTER 7 </b></center></p><br><table border=\"1\" style=\"width:100%\" font-size=\"300%\" > <tr bgcolor = red> <td> SUBJECT </td> <td> GRADE </td> </tr>" + hs6251 + ma6251 + ph6251 + cy6251 + ge6251 + ge6252 + ge6261 + carr + tarr + gpa +cgpa+"</table> <br> <br>";
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_s7ActionPerformed

    private void s8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s8ActionPerformed
        try {
            query = "select * from SEM8 where "+filter+ " = '"+no + "'";
            s.execute(query);
            rs1 = s.getResultSet();
            String hs6251 = "", ma6251 = "", ph6251 = "", cy6251 = "", ge6251 = "", ge6252 = "", ge6261 = "",ge6262 = "",ge6263 = "";
            while( rs1.next()){
               hs6251 = " <tr> <td> MULTI CORE ARCHITECTURE </td> <td> " + rs1.getString("CS6801") + "</td> </tr>";
               ma6251 = " <tr> <td> ELECTIVE 4 "/* PLS UPDATE */+" </td> <td> " + rs1.getString("ELE4") + "</td> </tr>";
               ph6251 = " <tr> <td> ELECTIVE 5 "/* PLS UPDATE */+" </td> <td> " + rs1.getString("ELE5") + "</td> </tr>";
               cy6251 = " <tr> <td> PROJECT WORK </td> <td> " + rs1.getString("CS6811") + "</td> </tr>";
                gpa = " <tr> <td> <b>GPA </b></td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("GPA") )) + "</td> </tr>";
               cgpa = " <tr> <td> <b>CGPA</b> </td> <td> " + String.format( "%.3f", Double.parseDouble(rs1.getString("CGPA") )) + "</td> </tr>";
               carr = " <tr> <td> <b>CURRENT ARREAR </b></td> <td> " + rs1.getInt("CURRENTARR") + "</td> </tr>";
               tarr = " <tr> <td> <b>TOTAL ARREAR </b></td> <td> " + rs1.getInt("TOTALARR") + "</td> </tr>";
            }
            ssem8 = " <p><center><b> SEMESTER 8 </b></center></p><br><table border=\"1\" style=\"width:100%\" font-size=\"300%\" > <tr bgcolor = red> <td> SUBJECT </td> <td> GRADE </td> </tr>" + hs6251 + ma6251 + ph6251 + cy6251 + carr + tarr + gpa +cgpa+"</table> <br> <br>";
        }
        catch(SQLException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_s8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        AdminPanel a = new AdminPanel();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel au;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel pec;
    private javax.swing.JTextField regno1;
    private javax.swing.JRadioButton regnoradio;
    private javax.swing.JRadioButton rollnoradio;
    private javax.swing.JCheckBox s1;
    private javax.swing.JCheckBox s2;
    private javax.swing.JCheckBox s3;
    private javax.swing.JCheckBox s4;
    private javax.swing.JCheckBox s5;
    private javax.swing.JCheckBox s6;
    private javax.swing.JCheckBox s7;
    private javax.swing.JCheckBox s8;
    private javax.swing.ButtonGroup select;
    private javax.swing.JLabel selectlbl;
    // End of variables declaration//GEN-END:variables
}
